language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

before_install:
  - git submodule update --init --remote --recursive

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "chenjiaobin"
  - git config user.email "72733@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GitHub_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/chenjiaobin/chenjiaobin.github.io.git
